export const themeOptions = [
  'rcBlue',
  'rcJupiterBlue',
  'rcDark',
  'rcHighContrast',
  'rcPhoenix',
  'avayaCustomized',
  'verizonSimple',
  'vodafoneBalanced',
  'rainbowRich',
  'atosRich',
  'telusRich',
  'attRich',
  'btRich',
  'eastlinkSimple',
  'mcmRich',
  'ecotelSimple',
];
