export interface DefaultPaletteKeys {}

export type RcPaletteKeys =
  | keyof DefaultPaletteKeys
  | 'action.grayDark'
  | 'action.grayLight'
  | 'action.primary'
  | 'avatar.ash'
  | 'avatar.blueberry'
  | 'avatar.brass'
  | 'avatar.global'
  | 'avatar.gold'
  | 'avatar.lake'
  | 'avatar.oasis'
  | 'avatar.pear'
  | 'avatar.persimmon'
  | 'avatar.sage'
  | 'avatar.tomato'
  | 'content.brand'
  | 'danger.b01'
  | 'danger.b02'
  | 'danger.b03'
  | 'danger.b04'
  | 'danger.f01'
  | 'danger.f02'
  | 'danger.f11'
  | 'dialHeader.avatarBg'
  | 'dialHeader.avatarIcon'
  | 'dialHeader.bg'
  | 'dialHeader.focusBorder'
  | 'dialHeader.icon'
  | 'dialHeader.text'
  | 'dialHeader.textHint'
  | 'disabled.b01'
  | 'disabled.f01'
  | 'disabled.f02'
  | 'header.bgLeft'
  | 'header.bgOverlay'
  | 'header.bgOverlayDisabled'
  | 'header.bgRight'
  | 'header.border'
  | 'header.divider'
  | 'header.fabBg'
  | 'header.fabIcon'
  | 'header.focusBorder'
  | 'header.icon'
  | 'header.iconDisabled'
  | 'header.text'
  | 'header.textHint'
  | 'highContrast'
  | 'highlight.b01'
  | 'highlight.b02'
  | 'highlight.b03'
  | 'highlight.f01'
  | 'highlight.f02'
  | 'informative.b01'
  | 'informative.f01'
  | 'informative.f02'
  | 'interactive.b01'
  | 'interactive.b02'
  | 'interactive.f01'
  | 'label.black02'
  | 'label.blue01'
  | 'label.blue02'
  | 'label.green01'
  | 'label.green02'
  | 'label.orange01'
  | 'label.orange02'
  | 'label.purple01'
  | 'label.purple02'
  | 'label.red01'
  | 'label.red02'
  | 'label.teal01'
  | 'label.teal02'
  | 'label.yellow01'
  | 'label.yellow02'
  | 'nav.b01'
  | 'nav.b02'
  | 'nav.bookmark'
  | 'nav.ctlDefault'
  | 'nav.ctlSelected'
  | 'nav.f01'
  | 'nav.f02'
  | 'nav.f03'
  | 'nav.f04'
  | 'nav.iconDefault'
  | 'nav.iconSelected'
  | 'nav.line'
  | 'nav.mention'
  | 'nav.menuBg'
  | 'nav.menuText'
  | 'neutral.b01'
  | 'neutral.b02'
  | 'neutral.b03'
  | 'neutral.b04'
  | 'neutral.b05'
  | 'neutral.b06'
  | 'neutral.elevation'
  | 'neutral.f01'
  | 'neutral.f02'
  | 'neutral.f03'
  | 'neutral.f04'
  | 'neutral.f05'
  | 'neutral.f06'
  | 'neutral.f07'
  | 'neutral.f11'
  | 'neutral.l01'
  | 'neutral.l02'
  | 'neutral.l03'
  | 'neutral.l04'
  | 'neutral.transparent'
  | 'presence.available'
  | 'presence.busy'
  | 'presence.invisible'
  | 'subAction'
  | 'success.b01'
  | 'success.b02'
  | 'success.b03'
  | 'success.b04'
  | 'success.b05'
  | 'success.f01'
  | 'success.f02'
  | 'success.f11'
  | 'tab.default'
  | 'tab.selected'
  | 'umi.bg'
  | 'umi.mentioned'
  | 'umi.text'
  | 'warning.b01'
  | 'warning.b02'
  | 'warning.b03'
  | 'warning.f01'
  | 'warning.f02'
  | 'warning.f11';

export type RcTextPaletteKeys = RcPaletteKeys;
// | 'content.brand'
// | 'interactive.b01'
// | 'interactive.b02'
// | 'interactive.f01'
// | 'neutral.b01'
// | 'neutral.b02'
// | 'neutral.b03'
// | 'neutral.b04'
// | 'neutral.b05'
// | 'neutral.b06'
// | 'neutral.elevation'
// | 'neutral.f01'
// | 'neutral.f02'
// | 'neutral.f03'
// | 'neutral.f04'
// | 'neutral.f05'
// | 'neutral.f06'
// | 'neutral.f07'
// | 'neutral.f11'
// | 'neutral.l01'
// | 'neutral.l02'
// | 'neutral.l03'
// | 'neutral.l04'
// | 'neutral.transparent';
