name: Publish Package to npm
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install 👾
        run: yarn

      - name: Build core 📦
        if: ${{ contains(github.ref, 'juno-core') }}
        run: yarn workspace @ringcentral/juno run release

      - name: Publish core 🚀
        if: ${{ contains(github.ref, 'juno-core') }}
        run: |
          VERSION=$(node -p "require('./packages/juno-core/dist/package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            npm publish ./packages/juno-core/dist --provenance --access public --tag next
          else
            npm publish ./packages/juno-core/dist --provenance --access public
          fi

      - name: Build icon 📦
        if: ${{ contains(github.ref, 'juno-icon') }}
        run: yarn workspace @ringcentral/juno-icon run release

      - name: Publish icon 🚀
        if: ${{ contains(github.ref, 'juno-icon') }}
        run: |
          VERSION=$(node -p "require('./packages/juno-icon/dist/package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            npm publish ./packages/juno-icon/dist --provenance --access public --tag next
          else
            npm publish ./packages/juno-icon/dist --provenance --access public
          fi
