name: Publish Package to npm
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install 👾
        run: yarn

      - name: Build core 📦
        if: ${{ contains(github.ref, 'juno-core') }}
        run: yarn workspace @ringcentral/juno run release

      - name: Publish core 🚀
        if: ${{ contains(github.ref, 'juno-core') }}
        run: npm publish ./packages/juno-core/dist --provenance --access public

      - name: Build icon 📦
        if: ${{ contains(github.ref, 'juno-icon') }}
        run: yarn workspace @ringcentral/juno-icon run release

      - name: Publish icon 🚀
        if: ${{ contains(github.ref, 'juno-icon') }}
        run: npm publish ./packages/juno-icon/dist --provenance --access public
